---
include:
  - board: hiro_sofle_right
    shield: nice_view_custom
    artifact-name: hiro-sofle-right

  - board: hiro_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: hiro-sofle-left
  
  - board: hiro_sofle_left
    shield: settings_reset
    artifact_name: hiro-sofle-reset
